[info]
chain_id = "Oraichain"
network = "mainnet"
deploy_date = ""
commit_hash = ""
salt = ""


[code-ids]
ibc_transfer_adapter_contract_code_id = "2506"
ibc_wasm_transfer_adapter_contract_code_id = "2507"
swap_adapter_oraidex_contract_code_id = "2508"
entry_point_contract_code_id = "2505"

[contract-addresses]
ibc_transfer_adapter_contract_address = "orai1ddqm6ynz6qdfr39nl9x8hfsmn2d56kr4ggd27g3e6jzwccr3hwhsk954fl"
ibc_wasm_transfer_adapter_contract_address = "orai12vlx3wqcxh6fufztxectta3nr84tl6p8mxrw9ekdewylpg2mcdlshs4hz4"
swap_adapter_oraidex_contract_address = "orai1vzjehdk3x5w5dml2vf4myn527fcprjc5q9uagw03nd9rmqfz3resjudg94"
entry_point_contract_address = "orai1yglsm0u2x3xmct9kq3lxa654cshaxj9j5d9rw5enemkkkdjgzj7sr3gwt0"
