[info]
chain_id = "osmosis-1"
network = "mainnet"
deploy_date = "13/05/2024 10:14:10"
commit_hash = "<COMMIT HASH HERE>"
salt = "1"

[checksums]
"skip_api_entry_point-aarch64.wasm" = ""
"skip_api_ibc_adapter_ibc_hooks-aarch64.wasm" = ""
"skip_api_ibc_adapter_neutron_transfer-aarch64.wasm" = ""
"skip_api_placeholder-aarch64.wasm" = ""
"skip_api_swap_adapter_astroport-aarch64.wasm" = ""
"skip_api_swap_adapter_dexter-aarch64.wasm" = ""
"skip_api_swap_adapter_hallswap-aarch64.wasm" = ""
"skip_api_swap_adapter_lido_satellite-aarch64.wasm" = ""
"skip_api_swap_adapter_osmosis_poolmanager-aarch64.wasm" = ""
"skip_api_swap_adapter_white_whale-aarch64.wasm" = ""

[code-ids]
ibc_transfer_adapter_contract_code_id = "878"
swap_adapter_osmosis-poolmanager_contract_code_id = "877"
entry_point_contract_code_id = "876"

[contract-addresses]
ibc_transfer_adapter_contract_address = "osmo1tagzq2ggsh04zvcjkqt28ky8hpg7yp3y47y6sywz5myaj7qrd2sq8mvah0"
swap_adapter_osmosis-poolmanager_contract_address = "osmo13rth9cvpce27rqf302c8s7dmems98v76kff7kxjvcgavyykhjprqk8qaw7"
entry_point_contract_address = "osmo1h3jkejkcpthl45xrrm5geed3eq75p5rgfce9taufkwfr89k63muqweu2y7"

[tx-hashes]
store_ibc_transfer_adapter_tx_hash = "9E967C7AAFC9B7FF3CCF23383A54A6B419BA5994463A8506EDC31BC5AF6D021A"
instantiate_ibc_transfer_adapter_tx_hash = "C30DEEC85787522F9830E451D08A07F24D3E6E4AC89775A1EE4F2BA4BC3228A3"
store_swap_adapter_osmosis-poolmanager_tx_hash = "B5CC5F4990B80D2EA12133B11B4709DC5F93D08893C4F8E2F35BC0BC08DB080A"
instantiate_swap_adapter_osmosis-poolmanager_tx_hash = "651DAAB495C5672A8F67AD6E49D23B24A14A7C903CFFAFC94212B962E228BE8F"
store_entry_point_tx_hash = "1952525DD71F39F9AB8D70A0DABEF45F2D79F61530294767376EAE463063FB79"
instantiate_entry_point_tx_hash = "A1E8570F03BB563D5A237706208D127B064B88119E0704B34FF20356A171889E"
